### ISSUE TITLE
ProviderError: Out Of Fund

### ISSUE THREAD

**Issue by AscThilanka** [jamesbachini/DEX-Arbitrage#11]
Hi, 
i've my private key and tried to deploy contract to mainnet, and it gives following error.
i already have around 140 USD worth ETH in my wallet for gas, 

any help would be appreciate !

![image](https://user-images.githubusercontent.com/98318503/166138542-3701d91d-9f6e-40b2-b94f-51fe4762f1f8.png)

**Comment by banlieu451** [comment]
For Aurora you need have >> AURORA TOKEN 

ETH is not the base currency of the AURORA BLOCKCHAIN

You can get Aurora when SWAP  eth to aurora

**Comment by AscThilanka** [comment]
@banlieu451 appreciate for your reply,
now i've managed to deploy contract but when I try to transfer some funds to contract, metamask giving an "Contract Interaction - fail"

any thoughts on that?


![image](https://user-images.githubusercontent.com/98318503/166310720-dc54d967-7445-47ab-8bcc-829111d8b056.png)


![image](https://user-images.githubusercontent.com/98318503/166310679-d07a9f61-9dd6-47a0-bf8e-04528cc3bdc3.png)

**Comment by jamesbachini** [comment]
Yes the contract doesn't have a payable function so you cant send the native asset. You can only send and withdraw erc20 tokens. Most dexes actually use a wrapped version of the native asset so eth-uni pool is actually weth. The native asset eth is wrapped in a erc20 contract known as weth.

Gas fees are still paid from the account in .env in the native asset when interacting with the contract

**Comment by banlieu451** [comment]
> @banlieu451 appreciate for your reply, now i've managed to deploy contract but when I try to transfer some funds to contract, metamask giving an "Contract Interaction - fail"
> 
> any thoughts on that?
> 
> ![image](https://user-images.githubusercontent.com/98318503/166310720-dc54d967-7445-47ab-8bcc-829111d8b056.png)
> 
> ![image](https://user-images.githubusercontent.com/98318503/166310679-d07a9f61-9dd6-47a0-bf8e-04528cc3bdc3.png)

you need run on console the scripts  "fund.js" (to send base asset to "(contract deployed)" 
and script trade.js to run it
