### ISSUE TITLE
For node scale example ?

### ISSUE THREAD

**Issue by banlieu451** [jamesbachini/DEX-Arbitrage#14]
https://github.com/jamesbachini/DEX-Arbitrage/blob/a1f23b3e3fe6d64350befef98713af5efbd2ff3f/scripts/trade.js#L14*
https://github.com/jamesbachini/DEX-Arbitrage/blob/a1f23b3e3fe6d64350befef98713af5efbd2ff3f/scripts/trade.js#L15

Hello James and thanks a lot !

Can you explain please,  how to use this line please ?

**Comment by banlieu451** [comment]
Thanks for reply so for this line 
//[0,0,0,0,0,0,0,0,0].forEach(async (v,i) 

We just delete " // " 
its gonna be " [0,0,0,0,0,0,0,0,0].forEach(async (v,i) " to run ?

**Comment by jamesbachini** [comment]
it wont work unless you have your own rpc node because of rate limits. If you have a rpc node set up you can just uncomment it or run the queries directly from the node.

**Comment by ingeniumyazilim** [comment]
Uncommenting those lines with a private rpc results in termination of the script just after the balances are printed. Any ideas?

**Comment by banlieu451** [comment]
Thanks i'm trying to install a node 1 mouth ago still can't :/
-- 
 Envoyé avec Tutanota, la boîte aux lettres sécurisée et sans publicité. 



16 mai 2022, 11:12 de ***@***.***:

**Comment by jamesbachini** [comment]
I'm not an expert on geth or bsc to be honest. Perhaps see if there is a BSC technical discord channel or try to connect with someone from their dev team for assistance. Sorry I couldn't be of more help here.
