### ISSUE TITLE
Do we need private rpc ?

### ISSUE THREAD

**Issue by fasogbon** [jamesbachini/DEX-Arbitrage#15]
Hello,
Thank you very much for this work.
I will like to know how profitable this can be? Would we need private customised rpc to be able to have profitable system?

**Comment by jamesbachini** [comment]
depends on the competition. This strategy using a public RPC node was making just a few dollars each day. If you can setup your own nodes and find less competitive niches or compete in places with higher volumes then there's plenty of opportunity in MEV and arbitrage.

**Comment by fasogbon** [comment]
I read your document. Thanks
