### ISSUE TITLE
How to set up?

### ISSUE THREAD

**Issue by Viraj-Bagga** [jamesbachini/DEX-Arbitrage#18]
Im trying to set this up, but cant figure this a lot, like what coins should I put in my metamask wallet etc. Can anybody give a full setup tutorial.

**Comment by smitch370** [comment]
[https://bytemeta.vip/repo/jamesbachini/DEX-Arbitrage]

**Comment by jamesbachini** [comment]
There's a pretty long form tutorial here:
https://jamesbachini.com/dex-arbitrage/

You'll need some funds for gas fees in the .env wallet. Then the contract holds the tokens. It's executed programmatically so you don't need to use Metamask.

**Comment by ahmdqader** [comment]
but here is question, what do you mean by editing base assets? and how to do it? and is this okay to use default base assets?

**Comment by jamesbachini** [comment]
So a base asset is a token and to edit it you will need to change the contract address.

Even if you use the same token you will likely find the contract address is different on different chains.

You can generally find token contract addresses using a block explorer
