### ISSUE TITLE
You are using a version of Node.js that is not supported by Hardhat, and it may work incorrectly, or not work at all.  Please, make sure you are using a supported version of Node.js.  To learn more about which versions of Node.js are supported go to https://hardhat.org/nodejs-versions

### ISSUE THREAD

**Issue by ifeingewgewmlkm** [jamesbachini/DEX-Arbitrage#19]
Any idea how to resolve this?

"You are using a version of Node.js that is not supported by Hardhat, and it may work incorrectly, or not work at all.

Please, make sure you are using a supported version of Node.js.

To learn more about which versions of Node.js are supported go to https://hardhat.org/nodejs-versions"

**Comment by jamesbachini** [comment]
Maybe try updating Node to the latest version or if you are using a nightly build perhaps try downgrading to the last LTS version.

More info here: https://www.hostingadvice.com/how-to/update-node-js-latest-version/
