### ISSUE TITLE
error deploying to aurora

### ISSUE THREAD

**Issue by lhalpin333** [jamesbachini/DEX-Arbitrage#2]
Hi James,
i tried deploying to aurora but got an error message back, 
ProviderError: Out Of Fund
    at HttpProvider.request (/home/luke/projects/DEX-Arbitrage/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)

on another point Im looking at integrating smart loans from https://dodoex.io/ as they dont have any charges. They also have a uniswap style dex running on Near/Aurora which you probably already know.
anyhow cheers for now,
luke

**Comment by jamesbachini** [comment]
Hi Luke, Aurora had to implement transaction fees which is why you are now getting out of funds messages because the owner address needs some ETH to pay gas fees. There's more info about it on their Twitter page.

**Comment by lhalpin333** [comment]
Hi James,
I suspected something like that. I tried without success putting Eth on
aurora. I can put matic on aurora but need gas to swap it. Do you know how
to get Eth on aurora?
Cheers
luke

**Comment by jamesbachini** [comment]
There's actually a faucet for a tiny amount of ETH providied by the Aurora team to help people that had funds stuck

https://aurora.dev/faucet

For larger amounts use a bridge. There's loads of links to bridges to different ecosystems on Trisolaris

**Comment by lhalpin333** [comment]
Great tip James, I used the faucet and was able to swap my matic for eth on
aurora, Thanks
Luke
