### ISSUE TITLE
Systematic Dual trades failures on Fantom all with a gas issue message

### ISSUE THREAD

**Issue by tranbert78** [jamesbachini/DEX-Arbitrage#22]
Dual trades are systematically blocked on Fantom with a gas issue message (cf. attachement)

Workarround proposals:
1)I suspect it could be because of current fund.js : 100% WFTM are transferred to arbContract to be used Wrapped, however we should try to to unwrap some of them through a deposit to arbContract (not a transfer) to serve as gas fee directly from the arbContract, to try to prevent dual trade being blocked... 
I did not have the time to  read this thorrowly https://ethereum.stackexchange.com/questions/131545/wftm-swap-transaction-always-fails, but it seems to answer the same issue and to propose a detailed solution to 1)

2)If the assumption given in  1) is wrong the alternative is to split the funds 50/50 between the wallet and the arbContract and to temporarily perform all trades directly from the wallet the time to solve the dual trade failure, while keeping everything else performed on arbContract (route search and trade estimates). Once the dual trade failure is solved we can perform everything back from the arbContract.
[Making dualTradeErrorShort.txt](https://github.com/jamesbachini/DEX-Arbitrage/files/9448449/Making.dualTradeErrorShort.txt)

**Comment by jamesbachini** [comment]
The gas fees are paid from the wallet in .env file. The contract doesn't need to pay transaction fees because they are paid by the user executing the transaction.

The gas issue error message just means the transaction will fail or revert. 

This is usually caused because of a bad router address or token contract address. Check the checksums (capitalisation) of these addresses and put them in a block explorer to double check it's right for the network you want to work on.

**Comment by tranbert78** [comment]
Hi James
Thanks you so much for providing this video for everyone, it's as if I've gained 12 months of experience in just 3 nights, thanks to this particular video !
I haven't made any changes to the code, but I agree to close the issue.
it's up to each person to individually solve the potential remaining defects, to deserve the bps, and to keep the opportunity worth something...

**Comment by jamesbachini** [comment]
Thanks for the feedback.

There are some past issues here that might help too.

https://github.com/jamesbachini/DEX-Arbitrage/issues/20

https://github.com/jamesbachini/DEX-Arbitrage/issues/13

https://github.com/jamesbachini/DEX-Arbitrage/issues/1

**Comment by tranbert78** [comment]
Hi James
Thanks for this feedback. 
The solution proposed in https://ethereum.stackexchange.com/questions/131545/wftm-swap-transaction-always-fails
is relevant to our swapExactTokensForTokens() and I could suggest a change it you would be ok with that
