### ISSUE TITLE
CALL_EXCEPTION when calling estimateDualDexTrade

### ISSUE THREAD

**Issue by y0unghe** [jamesbachini/DEX-Arbitrage#25]
I am keep getting `code: 'CALL_EXCEPTION'` when calling method `method: 'estimateDualDexTrade(address,address,address,address,uint256)',`

It seems `IUniswapV2Router` `getAmountsOut` keeps fail.  Do I need some ETH as gas in the contract?

**Comment by jamesbachini** [comment]
You would need some Eth in the wallet in .env file but the contract doesn't need Eth for gas. Check the token addresses and checksums
