### ISSUE TITLE
Script execution

### ISSUE THREAD

**Issue by isslerman** [jamesbachini/DEX-Arbitrage#26]
I think there is an error on readme.txt description execution: 

"Then to execute run:-
npx hardhat run --network aurora .\scripts\deploy.js"

It is not the deploy.js , is trade.js correct? I think the deploy is only to deploy the contract and then after change the json config address you execute the trade.js. 
Thanks for the video and the script. I'm trying some alternative exercise with the BSC network. 

Marcos Issler

**Comment by jamesbachini** [comment]
Updated, thank you
