### ISSUE TITLE
call exception errors

### ISSUE THREAD

**Issue by Fifi55555** [jamesbachini/DEX-Arbitrage#31]
Hello, so I have been testing the code, it seems promising but, I get Call Exception errors..  I have made some research and it appears that such an error occurs when the ABI code of the deployed contract is not configured in the code of the bot( as stated [here](https://docs.ethers.org/v5/troubleshooting/errors/#help-CALL_EXCEPTION)) 

Where can I insert the abi code in this code ?

**Comment by jamesbachini** [comment]
You just need an interface for the Dex functions you are calling from the contract. There's an ABI for our contract but that shouldn't be the issue. Would you happen to be trying it with a DeX which isn't based on Uni v2? If so the function names and parameters may be different to the ones in the contract

**Comment by Fifi55555** [comment]
Oh yes, my bad. Thanks that fixed it. 

Although,

1. How can i check a router address whether it is uni v2, apart from checking the dev docs, is there another way? 
 
2. Can i be able to upgrade my code to support uni v3 and how?

**Comment by jamesbachini** [comment]
1. Take a look at the router address on etherscan, in the contract section under write functions you'll see the function name and parameters

2. Yes you can, you just need to change some of the logic in the Arb.sol contract to execute for a different exchange. Plenty of examples on Github and in the Uniswap docs, which are very good, about how to do swaps in v3.
