### ISSUE TITLE
Nothing to compile

### ISSUE THREAD

**Issue by merttanitan1** [jamesbachini/DEX-Arbitrage#37]
When i run the npx hardhat run .\scripts\deploy.js --network aurora command, it returns 
Owner: 0xHereIsMyAddress
Nothing to compile
and nothing happening

**Comment by jordandjones** [comment]
That means you've already compiled the contracts locally. Just wait a few more minutes for the contract to finish deploying and you'll see a message like 
"Arb deployed to: 0x........
Put the above contract address into the .env file under arbContract"

**Comment by merttanitan1** [comment]
i edited config and .env files also waited like an hour to deploy but still nothing happened.

**Comment by jamesbachini** [comment]
Maybe try adding some console.log() lines to the deploy file to see where it's getting stuck. Could be a connection problem with the RPC provider maybe, but I'm guessing as there's not much to go on

**Comment by merttanitan1** [comment]
i checked this and added console.log() after "const contract = await smartContract.deploy();" line. And it didn't return.

**Comment by jamesbachini** [comment]
Try console.log('test');

**Comment by merttanitan1** [comment]
before const contract = await smartContract.deploy(); line;
Owner: 0xHereIsMyAddress
Nothing to compile
test

after before const contract = await smartContract.deploy(); line;
Owner: 0xMyAddress
Nothing to compile

**Comment by jamesbachini** [comment]
There's a problem deploying the contract. Not much to go on to say why. Maybe no funds in wallet to pay gas fees or something not right with the RPC node and API keys
