### ISSUE TITLE
Error: call revert exception

### ISSUE THREAD

**Issue by Devilla** [jamesbachini/DEX-Arbitrage#40]
# Issue
Tried using `estimateTriDexTrade(address,address,address,address,address,address,uint256)` method to scale the bot as per the turorial but getting this error while running the trade script with base assests.
```
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="estimateTriDexTrade(address,address,address,address,address,address,uint256)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)

 reason: null,
  code: 'CALL_EXCEPTION',
  method: 'estimateTriDexTrade(address,address,address,address,address,address,uint256)',
  data: '0x',
  errorArgs: null,
  errorName: null,
  errorSignature: null,

```

# Reference
https://github.com/Devilla/DEX-Arbitrage-Bot/blob/dev/contracts/Arb.sol

**Comment by jamesbachini** [comment]
The tx is failing. Not much to go on as to why. Maybe using Uni v2 functions on a v3 router or something like that?
