### ISSUE TITLE
[question] Porting it to polygon

### ISSUE THREAD

**Issue by Deadlolo** [jamesbachini/DEX-Arbitrage#5]
Hi there i'm willing to port it on polygon but i'm unsure if changing the contracts and routes adress would be enought .
is there anything else to edit that i missed ?
(Thank for making your code open source btw)

**Comment by jamesbachini** [comment]
Should work fine, you'll need some MATIC in the wallet address. Will only work with Uniswap v2 forks wont work with v3 without updating the functions. Update the token and router addresses and should be good to go.
