### ISSUE TITLE
Accidental unchain config contract address

### ISSUE THREAD

**Issue by saingsab** [jamesbachini/DEX-Arbitrage#6]
Hi Jam I am accidentally forgot to update the contract address: 0x00006c6eA30e6167AFfCc5099c59A4E5Bf95E8Ce on aurora.json which the arbContract. 

I send the fund there with default 20$. Is it ok to ask you back?
Thank you.

**Comment by jamesbachini** [comment]
Yeah I think I still have access to the dev wallet that deployed the contract. You want it sent back to this address? 0xAe18A61043c34bD938Ce4927d0AF7c67016a6DAf

**Comment by saingsab** [comment]
Hi 
Yes please just revert back the transaction to 0xAe18A61043c34bD938Ce4927d0AF7c67016a6DAf
thank you so much.

**Comment by jamesbachini** [comment]
No problem that's been done this morning. One of the tx 0x54678e490dd3e279697d626d6878f34b7a64c5828733bd2f176b7b1c24e4b64c
