### ISSUE TITLE
Error HH601: Script .scriptsdeploy.js doesn't exist.

### ISSUE THREAD

**Issue by Pritom-sarker** [jamesbachini/DEX-Arbitrage#7]
I followed the instruction properly but still got this error.

**Error HH601: Script .scriptsdeploy.js doesn't exist.**

**Comment by markmaxhere** [comment]
hey! @Pritom-sarker  were you able to solve it

**Comment by jamesbachini** [comment]
maybe missing a / between scripts and deploy.js? I assume you can see the deploy.js file in the scripts directory? The other thing it could be is a directory / vs \ between operating systems or something like that perhaps?
