### ISSUE TITLE
What is minBasisPointsPerTrade ?

### ISSUE THREAD

**Issue by ingeniumyazilim** [jamesbachini/DEX-Arbitrage#9]
What is minBasisPointsPerTrade used for ?

**Comment by jamesbachini** [comment]
It's used in trade.js here to calculate a profit target:
https://github.com/jamesbachini/DEX-Arbitrage/blob/48862833e0f896dd590a3ebdaf4ce7ef99dc4f4b/scripts/trade.js#L54

Setting it higher finds less trades but more profitable ones (assuming no one executes it first), setting it to zero will fire on all trades even if profits wont cover transaction costs.

**Comment by ingeniumyazilim** [comment]
Thanks James

**Comment by banlieu451** [comment]
Hello thanks !

Is that in GWEI ?

**Comment by unnhao** [comment]
Any suggestion for minBasisPointsPerTrade ?
I set 50 and didn't fire any transaction :(

**Comment by banlieu451** [comment]
Maybe its too much and actually too many other bot work

Because 50 the profit possible is bigger so other bot with good hardware performance are for sure actually scan it ...

**Comment by jamesbachini** [comment]
It depends what your transaction cost is and how large the trade is. Basically when there are gas fees you need the profits to cover the transaction fees. 1 basis point = 1% of 1%.
